sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t mardi/docker-app -f Dockerfile.dev

script:
  - docker run -e CI=true mardi/docker-app npm run test -- --coverage

after_success:
  - echo "Test Success"